### ISSUE TITLE
[SUGGESTION] Auto-generate `download.url` if `[update.curseforge]` exists

### ISSUE THREAD

**Issue by srnyx** [packwiz/packwiz#101]
It looks like the URL for a CurseForge mod is just `https://edge.forgecdn.net/files/FIRST4/REMAINING/FILENAME`
`FIRST4` = First 4 digits of `update.curseforge.project-id`
`REMAINING` = Remaining digits of `update.curseforge.project-id`
`FILENAME` = `filename`

So, with this information, packwiz could auto-generate `download.url` without the need for the user to specify it. And it may even be possible to also auto-generate `download.hash` (using default of `sha1`).
Obviously, this only affects manually added mods. So maybe this could lead to a new command (`packwiz manual install`) that allows you to specify all the required parameters (and any optional ones too) in a command line.

**Comment by srnyx** [comment]
Just realized you can bypass the "Failed to install mod: No files for your version exist" thing by just using the file's URL.
So I guess this doesn't really need to be done... 🤦‍♂️

**Comment by comp500** [comment]
Not sure what benefit this has over using the API to query that URL? Note that `packwiz curseforge install --addon-id 459496 --file-id 3535202` is also valid.

**Comment by srnyx** [comment]
> Not sure what benefit this has over using the API to query that URL? Note that `packwiz curseforge install --addon-id 459496 --file-id 3535202` is also valid.

Yeah, it'd be useless. I forgot about URLs and `--addon-id`/`--file-id`, sorry.
