### ISSUE TITLE
Double-check filename to see if it's the right modloader

### ISSUE THREAD

**Issue by srnyx** [packwiz/packwiz#104]
And if it isn't go to the next file. This really only applies to Modrinth.
😔 https://modrinth.com/mod/nochatlag/version/1.1.0
![image](https://user-images.githubusercontent.com/25808801/161456802-b38157c6-857d-41c1-8ada-0ed4458c89b7.png)

**Comment by comp500** [comment]
I really don't want to implement that. Heuristics based on file name are incredibly brittle, and in most cases the files are filtered by the Modrinth backend so it wouldn't find the correct file if both are mislabeled. I might consider checking the `mod.toml`/`fabric.mod.json` in the future, but this comes at significant complexity cost; and Modrinth does now [validate](https://github.com/modrinth/labrinth/blob/80e00a80d55398875c54d307a390b09785c3f539/src/validate/forge.rs#L34) [these](https://github.com/modrinth/labrinth/blob/80e00a80d55398875c54d307a390b09785c3f539/src/validate/fabric.rs#L34) on file upload. For already uploaded files, please contact the mod author or Modrinth to update the metadata :)
