### ISSUE TITLE
[Feature] Create Apple Silicon binaries

### ISSUE THREAD

**Issue by ChristopherHaws** [packwiz/packwiz#105]
Thanks for this amazing tool. It would be awesome to have a native Apple Silicon build if that is possible.

Thanks!

**Comment by comp500** [comment]
Turns out my goreleaser setup already makes Apple Silicon builds, I just need to expose them as build artifacts!

**Comment by ChristopherHaws** [comment]
Works like a charm! Thanks so much for the quick turnaround!

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/5934505/162644587-2042221c-56d7-4e64-87ae-d580068e4cfd.png">
