### ISSUE TITLE
unexpected addon ID / 403 Forbidden (CurseForge old API shutdown)

### ISSUE THREAD

**Issue by copygirl** [packwiz/packwiz#114]
Could not find anything on this error, neither in issues nor with search engines.
Wondering if CurseForge just now changed their API, or if it is a temporary issue.

When attempting to install CurseForge mods using packwiz, I get these errors:
```
$ packwiz cf get pehkui      
unexpected addon ID in CurseForge response: 319596/0
$ packwiz cf get origins-forge
unexpected addon ID in CurseForge response: 474438/0
$ packwiz cf get bucolic-origins
unexpected addon ID in CurseForge response: 596305/0
```

**Comment by comp500** [comment]
The old CurseForge API that current versions of packwiz use has been shut down; see the announcement in the packwiz Discord server. I'm in the process of updating it to use the new CurseForge API now.

**Comment by comp500** [comment]
The packwiz CLI and packwiz-installer have now been updated to support the new CurseForge API!

**Comment by ChristopherHaws** [comment]
@comp500 I updated to the latest version and I am still having this issue. Any idea why this would be?

```
packwiz cf install xaeros-minimap
unexpected addon ID in CurseForge response: 263420/0
```

**Comment by comp500** [comment]
The error message has been changed in the latest version, you are not using the latest version. Where did you download packwiz from?

**Comment by ChristopherHaws** [comment]
I ran `go install github.com/packwiz/packwiz@latest`

**Comment by ChristopherHaws** [comment]
My bad, i had a 2nd copy of packwiz on my path which was the old version. Thanks for your help :)
