### ISSUE TITLE
Downloads Quilt mod files for Forge modpacks

### ISSUE THREAD

**Issue by goodtrailer** [packwiz/packwiz#127]
Packwiz seems to think that mod files which support Quilt but *not* Fabric are valid for Forge modpacks, leading to cases where newer Quilt files are taken over older Forge files. The workaround is to just specify the file id, but then `packwiz update --all` no longer becomes viable.

Tested with the Packwiz build from [5/31/2022 9am](https://github.com/packwiz/packwiz/actions/runs/2416243988):
* [GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib/files/all?filter-game-version=1738749986%3A73250) 1.18-3.0.6 (Quilt) and 1.18-3.0.18 (Forge)
* [Simple Voice Chat](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/all?filter-game-version=1738749986%3a73250) 1.18.2-2.2.44 (Quilt) and 1.18.2-2.2.44 (Forge)
* [Ellemes' Container Library](https://www.curseforge.com/minecraft/mc-mods/ellemes-container-library/files/all?filter-game-version=1738749986%3a73250) 1.4.0-beta2 (Quilt) and 1.4.0-beta2 (Forge)

**Comment by comp500** [comment]
Quilt was added to the CurseForge API very recently, so packwiz currently treats Quilt files the same as those not marked with a modloader (usable in all packs).

**Comment by comp500** [comment]
This issue is fixed, though the fix could be improved a bit; see https://github.com/packwiz/packwiz/issues/128
