### ISSUE TITLE
Prefer Quilt files over Fabric files where both are available (MR fixed)

### ISSUE THREAD

**Issue by comp500** [packwiz/packwiz#128]
If a mod supports both with different jars, the Fabric version might be chosen on the Quilt loader (as Quilt has compatibility with Fabric mods). Ideally, the Quilt version should be chosen, particularly if there are differences that break the mod on Quilt. The current code isn't terribly well designed for this.

**Comment by comp500** [comment]
https://github.com/packwiz/packwiz/commit/65688cf2b113702a97539f9dafe6bae26eac2519 fixes this for Modrinth; hasn't been done for CurseForge yet as it's more complicated.

**Comment by ryleu** [comment]
curseforge seems to always be more complicated
