### ISSUE TITLE
Initialization fails in Termux, Android

### ISSUE THREAD

**Issue by samolego** [packwiz/packwiz#131]
When trying to run `packwiz init` in termux, you get the following error:
```
Modpack name [Home]:
Author:
Version [1.0.0]:
Failed to get latest minecraft versions: Get "https://launchermeta.mojang.com/mc/game/version_manifest.json": dial tcp: lookup launchermeta.mojang.com on [::1]:53: read udp [::1]:39209->[::1]:53: read: connection refused
```
Why android? Well I was curious if I could manage my modpack(s) from the phone :).

**Comment by Den4enko** [comment]
Did you install the version from GitHub Actions? Or did you build it from source?

**Comment by samolego** [comment]
I used the one from gh actions, the 64bit arm linux build. Should I build it myself?

**Comment by comp500** [comment]
Yeah, go binaries need a different GOOS for Android, due to library stuff. I don't provide Android binaries through Github Actions currently since it requires setting up the Android NDK with it; though if you do get it working I'd accept a PR.
