### ISSUE TITLE
Index becomes empty when using Packwiz via PATH/not in same directory

### ISSUE THREAD

**Issue by Aeswere** [packwiz/packwiz#135]
When using packwiz to refresh the index.toml file, if you're not in the current directory the progress bar stays at 0%, and says it has finished, when viewing the index.toml file, all files are not listed & packwiz list command displays nothing. Problem is solved when using said command inside of the current directory that packwiz.exe is inside of. Even using packwiz with arguments linking pack.toml as well as the mods metadata folder it fails to work unless done as previously iterated.

When used outside of packwiz directory:
`packwiz refresh --pack-file "D:\Data\000 Applications\packwiz\pack.toml"`
`Loading modpack...`
`Refreshing index... 0 % [------------------------------------------------------------------------------] done`
`Index refreshed!`

When used inside packwiz directory:
`packwiz refresh`
`Loading modpack...`
`Refreshing index... 100 %` `[==============================================================================] done`
`Index refreshed!`

**Comment by comp500** [comment]
Hmm, I can't seem to replicate this. Are your pack.toml and index.toml files in the same directory? Note that files included in the modpack are traversed from the folder containing `index.toml`, if you have that in a separate location it won't find them.
