### ISSUE TITLE
Releases with multiple versions in Modrinth would sometimes download the wrong jar file for a Minecraft version

### ISSUE THREAD

**Issue by 3stantedja** [packwiz/packwiz#142]
Ran across this one while using it as a package manager for my Minecraft server.

The mod Discord4Fabric has multiple files listed for a release, each for a different version of Minecraft. My server runs on 1.19, and is defined as so in the pack.toml file, however when doing `packwiz mr install discord4fabric` it downloaded discord4fabric-1.18.2-1.8.0.jar instead of discord4fabric-1.19-1.8.0.jar.
```console
fyyrraaa@DESKTOP-OwO-UwU:~/servers/fabric-1.19/packwiz-modpack$ packwiz mr install discord4fabric
Found mod Discord4Fabric: 'A beautiful Discord bot client for Fabric'.
Installing discord4fabric-1.18.2-1.8.0.jar from version 1.8.0
```
I could correct it by hand for now as a workaround.

**Comment by comp500** [comment]
The mod author has uploaded their versions incorrectly, please ask them to fix it - they need to create separate versions for 1.18 and 1.19, as the metadata currently implies that *both* files support *both* 1.18 and 1.19!

**Comment by 3stantedja** [comment]
I'll create a new issue on their repo, thanks! I didn't know that's how it works on Modrinth.

**Comment by 3stantedja** [comment]
Filed under Reimnop/Discord4Fabric#36
