### ISSUE TITLE
Allow installation of mods that don't have exact Minecraft version match

### ISSUE THREAD

**Issue by gmemstr** [packwiz/packwiz#147]
As an example, https://modrinth.com/mod/betterf3 does work with 1.19.2, but isn't officially marked as such at this time. Users should have the option to install a mod they have tested to work, ignoring the Minecraft version specified in the `pack.toml` file.

Thinking this would constrain itself to the minor number of the Minecraft version (so 1.19.2 could also match versions for 1.19.1, 1.19, or 1.19.3+), and be behind a flag (`--ignore-patch`, `--loose-version` as some flag examples) to prevent accidental use of this behaviour.

Happy to take this on myself if this seems like something worth implementing.

**Comment by gmemstr** [comment]
Seems this does exist https://github.com/packwiz/packwiz/issues/81#issuecomment-1004643013 but wasn't immediately obvious. Maybe there should be a step during init?

**Comment by copygirl** [comment]
Can't you do this by specifying the exact version to install? For example:
```sh
packwiz curseforge install https://www.curseforge.com/minecraft/mc-mods/betterf3/files/3884453
packwiz modrinth install https://modrinth.com/mod/betterf3/version/N2TDuUIv
```
(I believe for Modrinth you require the version ID rather than the human readable name, see #103.)

**Comment by comp500** [comment]
Hmm, this does seem to be a common issue that new users encounter. The flag you suggested already has an issue created, at https://github.com/packwiz/packwiz/issues/31. It is documented on the website, but not all users will think to look there (or look in the right place) - I've created a couple more issues (https://github.com/packwiz/packwiz/issues/188 https://github.com/packwiz/packwiz/issues/187) with other improvements that could be implemented.
