### ISSUE TITLE
packwiz refresh appears to generate mod incorrect hashes on Windows

### ISSUE THREAD

**Issue by PKPenguin321** [packwiz/packwiz#148]
1. Install packwiz onto a Windows machine
2. Grab a functional modpack that you want to tweak
3. After tweaking the pack, do `packwiz refresh` to generate a fresh hash for your index.toml
4. Observe that your index.toml now contains entirely invalid hashes for each mod (see https://github.com/PKPenguin321/HexMC/commit/652fe2b59a2b9d06a1eccd041f99cd58eecc2fe7 for a tangible example; each mod throws a `java.lang.Exception: Invalid mod file hash` when you try to packwiz them onto your server later on)

Discussion with another developer revealed that he experienced the same thing but did not encounter the issue on Mac or Linux machines, making me think this is Windows specific.

**Comment by comp500** [comment]
Git line ending conversion invalidates the hashes, see https://packwiz.infra.link/tutorials/creating/git/ for how to disable this.
