### ISSUE TITLE
CurseForge detection install step should display progress

### ISSUE THREAD

**Issue by falxie** [packwiz/packwiz#151]
When running `packwiz curseforge detect` on a large number of files it's hard to know whether or not the command is actually working once you hit the install step. Simply outputting the files modified would help, but a progress meter would better

**Comment by comp500** [comment]
Hmm, I should just be able to make it significantly faster (and remove the need for a progress bar) by fetching all the mods at once, assuming the API doesn't limit how many you can request at once.

**Comment by falxie** [comment]
The difference before and after this fix is night and day. With my gigabit internet it finishes before I can really think about it. Thank you!

**Comment by falxie** [comment]
@comp500 I'm noticing some really strange mismatches when doing the steps in https://github.com/packwiz/packwiz/issues/150#issuecomment-1223477000. Mods seem mismatched and my best guess is that your bulk request doesn't come back in the order that you expect.

Running `java -jar packwiz-installer-bootstrap.jar -g -s client` against https://github.com/falxie/construct/releases/tag/1.0.0 to create the "extracted pack", `packwiz init`, and then `packwiz cf detect` results in the following:

[Construct-1.0.0.zip](https://github.com/packwiz/packwiz/files/9400654/Construct-1.0.0.zip)

And this monster of a CurseForge rejection:

<details>
<summary>CurseForge rejection</summary>

> The status of the file Construct-1.0.0.zip (Construct) has been changed to Rejected
> 
> Invalid file reference in manifest: File [1.18.2] YUNG's Better Strongholds v2.1.1 (Forge) (ID: 3778231) does not belong to Project YUNG's Better Strongholds (Forge) (ID: 442719).
> Invalid file reference in manifest: File [1.18.2] YUNG's Better Witch Huts v1.0.1 (Forge) (ID: 3855148) does not belong to Project YUNG's Better Witch Huts (Forge) (ID: 305840).
> Invalid file reference in manifest: File [1.18.2] YUNG's Bridges v2.1.0 (Forge) (ID: 3777944) does not belong to Project YUNG's Bridges (Forge) (ID: 501590).
> Invalid file reference in manifest: File [1.18.2] YUNG's Extras v2.1.0 (Forge) (ID: 3777937) does not belong to Project YUNG's Extras (Forge) (ID: 426558).
> Invalid file reference in manifest: File Abnormals Delight 1.18.2 - 3.0.1 (ID: 3907766) does not belong to Project Abnormals Delight (ID: 438003).
> Invalid file reference in manifest: File absentbydesign-1.18.2-1.6.2.jar (ID: 3686851) does not belong to Project Absent by Design (ID: 273279).
> Invalid file reference in manifest: File Additional Lanterns 1.0.1 for Forge 1.18 (ID: 3760338) does not belong to Project Additional Lanterns (ID: 248787).
> Invalid file reference in manifest: File alexsmobs-1.18.6 (ID: 3853078) does not belong to Project Alex's Mobs (ID: 419699).
> Invalid file reference in manifest: File betterbiomeblend-1.18.2-1.3.5-forge.jar (ID: 3804089) does not belong to Project Better Biome Blend (ID: 261251).
> Invalid file reference in manifest: File Allurement 1.18.2 - 2.0.0 (ID: 3881523) does not belong to Project Allurement (ID: 531761).
> Invalid file reference in manifest: File antighost-1.18.1-forge39.0.9-1.1.2.jar (ID: 3584113) does not belong to Project AntiGhost (ID: 446253).
> Invalid file reference in manifest: File appleskin-forge-mc1.18.2-2.4.1.jar (ID: 3927564) does not belong to Project AppleSkin (ID: 551520).
> Invalid file reference in manifest: File [Forge 1.18.2] v4.9.83 (ID: 3929416) does not belong to Project Architectury API (Fabric/Forge) (ID: 382216).
> Invalid file reference in manifest: File balm-3.2.0+0.jar (ID: 3914491) does not belong to Project Balm (Forge Edition) (ID: 355458).
> Invalid file reference in manifest: File betterfpsdist-1.18.2-1.5.jar (ID: 3750013) does not belong to Project Better Fps - Render Distance[Forge] (ID: 459701).
> Invalid file reference in manifest: File Buzzier Bees 1.18.2 - 4.0.0 (ID: 3881526) does not belong to Project Buzzier Bees (ID: 331936).
> Invalid file reference in manifest: File bwncr-3.13.21.jar (ID: 3800660) does not belong to Project Bad Wither No Cookie - Reloaded (ID: 392805).
> Invalid file reference in manifest: File Catalogue 1.6.2 (ID: 3803098) does not belong to Project Catalogue (ID: 251407).
> Invalid file reference in manifest: File Furniture Mod 7.0.0-pre29 (ID: 3683524) does not belong to Project MrCrayfish's Furniture Mod (ID: 348521).
> Invalid file reference in manifest: File citadel-1.11.3-1.18.2 (ID: 3783096) does not belong to Project Citadel (ID: 69162).
> Invalid file reference in manifest: File cleancut-mc1.18.2-4.0-forge.jar (ID: 3826151) does not belong to Project CleanCut (ID: 276951).
> Invalid file reference in manifest: File clienttweaks-forge-1.18.1-7.1.0.jar (ID: 3666468) does not belong to Project Client Tweaks (ID: 457570).
> Invalid file reference in manifest: File [Forge 1.18.x] v6.2.62 (ID: 3782776) does not belong to Project Cloth Config API (Fabric/Forge) (ID: 470193).
> Invalid file reference in manifest: File cofh_core-1.18.2-1.6.4.21.jar (ID: 3838025) does not belong to Project CoFH Core (ID: 231484).
> Invalid file reference in manifest: File comforts-forge-1.18.2-5.0.0.4.jar (ID: 3682307) does not belong to Project Comforts (Forge) (ID: 316582).
> Invalid file reference in manifest: File connectivity-1.18.2-3.2.jar (ID: 3833738) does not belong to Project Connectivity[Forge/Fabric] (ID: 542235).
> Invalid file reference in manifest: File Configured 1.5.3 (ID: 3721946) does not belong to Project Configured (ID: 328085).
> Invalid file reference in manifest: File cookingforblockheads-forge-1.18.2-12.0.2.jar (ID: 3830862) does not belong to Project Cooking for Blockheads (ID: 574622).
> Invalid file reference in manifest: File [1.18.2] Corpse 1.18.2-1.0.1 (ID: 3694258) does not belong to Project Corpse (ID: 309927).
> Invalid file reference in manifest: File Create 1.18.2 v0.5.0d (ID: 3934676) does not belong to Project Create (ID: 596224).
> Invalid file reference in manifest: File createcafe-1.9.2-1.18.2 (ID: 3940097) does not belong to Project Create Cafe (ID: 232131).
> Invalid file reference in manifest: File culturaldelights-1.18.2-0.12.1.jar (ID: 3913827) does not belong to Project Cultural Delights (ID: 480816).
> Invalid file reference in manifest: File ferritecore-4.2.1-forge.jar (ID: 3767288) does not belong to Project FerriteCore (Forge) (ID: 317134).
> Invalid file reference in manifest: File curios-forge-1.18.2-5.0.7.1.jar (ID: 3841948) does not belong to Project Curios API (Forge) (ID: 577096).
> Invalid file reference in manifest: File [Forge 1.18.2] 1.11.0 (ID: 3812301) does not belong to Project Debugify (ID: 570463).
> Invalid file reference in manifest: File defaultoptions-forge-1.18.2-14.1.1.jar (ID: 3830896) does not belong to Project Default Options (ID: 349447).
> Invalid file reference in manifest: File drawerfps-1.18.2-2.4.jar (ID: 3781652) does not belong to Project DrawerFPS (ID: 448233).
> Invalid file reference in manifest: File Dynamic Asset Generator [Forge] v0.6.3 (ID: 3808487) does not belong to Project Dynamic Asset Generator (ID: 491890).
> Invalid file reference in manifest: File trashslot-forge-1.18.1-11.0.2.jar (ID: 3658064) does not belong to Project TrashSlot (ID: 628539).
> Invalid file reference in manifest: File Ecologics 1.7.9 (Forge 1.18.2) (ID: 3939725) does not belong to Project Ecologics (ID: 577411).
> Invalid file reference in manifest: File ensorcellation-1.18.2-1.6.1.8.jar (ID: 3837816) does not belong to Project Ensorcellation (ID: 495693).
> Invalid file reference in manifest: File 1.5.1 - Forge(1.18) (ID: 3743929) does not belong to Project Entity Culling Fabric/Forge (ID: 560323).
> Invalid file reference in manifest: File [Forge 1.18.2] Etched 2.2.0 (ID: 3931285) does not belong to Project Etched (ID: 429235).
> Invalid file reference in manifest: File everycomp-1.18.2-1.5.12.jar (ID: 3916828) does not belong to Project Every Compat (ID: 431430).
> Invalid file reference in manifest: File Excavated Variants [Forge] v0.6.4 (ID: 3867010) does not belong to Project Excavated Variants (ID: 486392).
> Invalid file reference in manifest: File farsight-1.18.2-1.9.jar (ID: 3810400) does not belong to Project Farsight [Forge] (ID: 376351).
> Invalid file reference in manifest: File Feature NBT Deadlock Be Gone v2.0.0 (1.18.2 MC Forge) (ID: 3669114) does not belong to Project Feature NBT Deadlock Be Gone (ID: 388172).
> Invalid file reference in manifest: File flickerfix-2.0.0.jar (ID: 3544460) does not belong to Project FlickerFix (ID: 363703).
> Invalid file reference in manifest: File flywheel-forge-1.18.2-0.6.5.jar (ID: 3934664) does not belong to Project Flywheel (ID: 395078).
> Invalid file reference in manifest: File 1.9.11 (Forge 1.18.2) (ID: 3824951) does not belong to Project spark (ID: 583345).
> Invalid file reference in manifest: File Global Data- & Resourcepacks - Forge - 1.18.2 - v1.12.2 (ID: 3779086) does not belong to Project Global Packs (ID: 265917).
> Invalid file reference in manifest: File geckolib-forge-1.18-3.0.34.jar (ID: 3930007) does not belong to Project GeckoLib (ID: 238222).
> Invalid file reference in manifest: File framedcompactdrawers-1.18-4.1.0.jar (ID: 3808242) does not belong to Project Framed Compacting Drawers (ID: 532286).
> Invalid file reference in manifest: File JadeAddons-1.18.2-2.4.0.jar (ID: 3886082) does not belong to Project Jade Addons (Forge) (ID: 417645).
> Invalid file reference in manifest: File JustEnoughProfessions-1.18.2-1.2.2.jar (ID: 3670345) does not belong to Project Just Enough Professions (JEP) (ID: 240630).
> Invalid file reference in manifest: File JustEnoughResources-1.18.2-0.14.1.171 (ID: 3831559) does not belong to Project Just Enough Resources (JER) (ID: 303657).
> Invalid file reference in manifest: File Goblin Traders 1.7.2 (ID: 3780535) does not belong to Project Goblin Traders (ID: 241895).
> Invalid file reference in manifest: File Infernal Expansion Release 2.5.0 for Minecraft 1.18.2 (ID: 3854062) does not belong to Project Infernal Expansion (ID: 351264).
> Invalid file reference in manifest: File jeed-1.18.2-1.11.jar (ID: 3820697) does not belong to Project Just Enough Effect Descriptions (JEED) (ID: 549394).
> Invalid file reference in manifest: File Starlight 1.0.2 1.18.2 (Forge) (ID: 3706539) does not belong to Project Starlight (Forge) (ID: 537533).
> Invalid file reference in manifest: File jei-1.18.2-9.7.1.255.jar (ID: 3940240) does not belong to Project Just Enough Items (JEI) (ID: 460819).
> Invalid file reference in manifest: File [Forge 1.18.2] Pollen 1.4.9 (ID: 3931046) does not belong to Project Pollen (ID: 558905).
> Invalid file reference in manifest: File Kiwi-1.18.2-forge-6.1.2.jar (ID: 3827373) does not belong to Project Kiwi 🥝 (Forge) (ID: 74924).
> Invalid file reference in manifest: File Core Lib 1.0.19 for Forge 1.18 (ID: 3863129) does not belong to Project SuperMartijn642's Core Lib (ID: 225738).
> Invalid file reference in manifest: File jeiintegration_1.18.2-9.0.0.37 (ID: 3812175) does not belong to Project JEI Integration (ID: 238747).
> Invalid file reference in manifest: File kleeslabs-forge-1.18.2-11.1.1.jar (ID: 3830926) does not belong to Project KleeSlabs (ID: 391382).
> Invalid file reference in manifest: File Ksyxis-Forge1.17thru1.19-1.1.jar (ID: 3502166) does not belong to Project Ksyxis (ID: 60089).
> Invalid file reference in manifest: File Blueprint 1.18.2 - 5.4.3 (ID: 3923941) does not belong to Project Blueprint (ID: 55438).
> Invalid file reference in manifest: File Mantle 1.9.27 for 1.18.2 (ID: 3829975) does not belong to Project Mantle (ID: 492574).
> Invalid file reference in manifest: File Kotlin for Forge 3.7.1 (ID: 3925887) does not belong to Project Kotlin for Forge (ID: 627986).
> Invalid file reference in manifest: File krypton-0.1.10-SNAPSHOT.jar (ID: 3819215) does not belong to Project Krypton Reforged (ID: 382016).
> Invalid file reference in manifest: File MmmMmmMmmMmm-1.18.2-1.5.2.jar (ID: 3820503) does not belong to Project MmmMmmMmmMmm (Target Dummy) (ID: 496394).
> Invalid file reference in manifest: File lazydfu-1.0-1.18+.jar (ID: 3544496) does not belong to Project Lazy DataFixerUpper(LazyDFU) [FORGE] (ID: 442354).
> Invalid file reference in manifest: File modnametooltip-1.18.1-1.18.0.jar (ID: 3574005) does not belong to Project Mod Name Tooltip (ID: 509575).
> Invalid file reference in manifest: File [1.18.2] MoreOverlays 1.20.9 (ID: 3924730) does not belong to Project More Overlays Updated (ID: 581495).
> Invalid file reference in manifest: File [1.18+] Mouse Tweaks 2.21 Forge (ID: 3578801) does not belong to Project Mouse Tweaks (ID: 247560).
> Invalid file reference in manifest: File MyServerIsCompatible-1.18-1.0.jar (ID: 3544398) does not belong to Project My Server Is Compatible (ID: 224633).
> Invalid file reference in manifest: File Naturalist 1.1.1 (Forge 1.18.2) (ID: 3930806) does not belong to Project Naturalist (ID: 415974).
> Invalid file reference in manifest: File Nether's Delight 2.2 (ID: 3756127) does not belong to Project Nether's Delight (ID: 351441).
> Invalid file reference in manifest: File supplementaries-1.18.2-1.4.11.jar (ID: 3942420) does not belong to Project Supplementaries (ID: 283644).
> Invalid file reference in manifest: File Neapolitan 1.18.2 - 3.0.0 (ID: 3881528) does not belong to Project Neapolitan (ID: 544197).
> Invalid file reference in manifest: File Not Enough Crashes 4.1.4+1.18.2 Forge (ID: 3711717) does not belong to Project Not Enough Crashes (Forge) (ID: 544350).
> Invalid file reference in manifest: File 2.2.3 [forge] (ID: 3745494) does not belong to Project Observable (ID: 388800).
> Invalid file reference in manifest: File Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.2.jar (ID: 3868886) does not belong to Project Oh The Biomes You'll Go (ID: 495476).
> Invalid file reference in manifest: File PassthroughSigns-1.18-2.5.0.jar (ID: 3546561) does not belong to Project Passthrough Signs (ID: 243121).
> Invalid file reference in manifest: File Oculus mc1.18.2-1.2.5a (ID: 3929520) does not belong to Project Oculus (ID: 570017).
> Invalid file reference in manifest: File Personality 1.18.2 - 2.0.0 (ID: 3881529) does not belong to Project Personality (ID: 368293).
> Invalid file reference in manifest: File [FORGE] v1.2 for 1.18.2 (ID: 3799118) does not belong to Project Plushie Mod (ID: 574856).
> Invalid file reference in manifest: File polymorph-forge-1.18.2-0.44.jar (ID: 3793106) does not belong to Project Polymorph (Forge) (ID: 509239).
> Invalid file reference in manifest: File [1.18.2] Twigs 1.1.4-patch3 (ID: 3756844) does not belong to Project 🪵 Twigs (ID: 499980).
> Invalid file reference in manifest: File Radium mc1.18.2-0.7.10 (ID: 3707226) does not belong to Project Radium Reforged (ID: 365281).
> Invalid file reference in manifest: File Repurposed Structures v5.1.14 (1.18.2 MC) (ID: 3820310) does not belong to Project Repurposed Structures (Forge) (ID: 407174).
> Invalid file reference in manifest: File Rubidium mc1.18.2-0.5.3a (ID: 3929515) does not belong to Project Rubidium (ID: 414154).
> Invalid file reference in manifest: File rubidium_extras-1.18.2_v1.3.2.jar (ID: 3936081) does not belong to Project Magnesium/Rubidium Extras (ID: 422301).
> Invalid file reference in manifest: File Second Chance (Forge) Release 1.5.0 for Minecraft 1.18.x (ID: 3832230) does not belong to Project Second Chance (Forge) (ID: 618298).
> Invalid file reference in manifest: File selene-1.18.2-1.17.9.jar (ID: 3842421) does not belong to Project Moonlight Lib (ID: 619320).
> Invalid file reference in manifest: File serverconfigupdater-2.0.jar (ID: 3585637) does not belong to Project ServerConfig Updater (ID: 361579).
> Invalid file reference in manifest: File shutupexperimentalsettings-1.0.5.jar (ID: 3759881) does not belong to Project Shutup Experimental Settings! (ID: 526854).
> Invalid file reference in manifest: File PickUpNotifier-v3.2.0-1.18.2-Forge.jar (ID: 3671364) does not belong to Project Pick Up Notifier (ID: 223852).
> Invalid file reference in manifest: File skinned_lanterns-1.18.2-1.3.4.jar (ID: 3752414) does not belong to Project Skinned Lanterns (Forge) (ID: 454372).
> Invalid file reference in manifest: File sophisticatedbackpacks-1.18.2-3.18.17.680.jar (ID: 3931811) does not belong to Project Sophisticated Backpacks (ID: 412082).
> Invalid file reference in manifest: File PuzzlesLib-v3.3.5-1.18.2-Forge.jar (ID: 3804332) does not belong to Project Puzzles Lib (ID: 563928).
> Invalid file reference in manifest: File Quark-3.2-358.jar (ID: 3840125) does not belong to Project Quark (ID: 513688).
> Invalid file reference in manifest: File Placebo-1.18.2-6.6.0.jar (ID: 3942932) does not belong to Project Placebo (ID: 74072).
> Invalid file reference in manifest: File sophisticatedcore-1.18.2-0.5.1.98.jar (ID: 3931794) does not belong to Project Sophisticated Core (ID: 235577).
> Invalid file reference in manifest: File sophisticatedstorage-1.18.2-0.5.1.107.jar (ID: 3931806) does not belong to Project Sophisticated Storage (ID: 496913).
> Invalid file reference in manifest: File Tinkers' Construct 3.5.1.31 for 1.18.2 (ID: 3829979) does not belong to Project Tinkers Construct (ID: 263420).
> Invalid file reference in manifest: File StorageDrawers-1.18.2-10.2.1.jar (ID: 3807626) does not belong to Project Storage Drawers (ID: 317780).
> Invalid file reference in manifest: File TerraBlender Forge 1.18.2-1.1.0.99 (ID: 3725996) does not belong to Project TerraBlender (Forge) (ID: 421850).
> Invalid file reference in manifest: File Terralith v2.2.1a ~ Fabric/Forge (ID: 3696607) does not belong to Project Terralith (ID: 510089).
> Invalid file reference in manifest: File v1.26.5 for Forge 1.18.2 (ID: 3937655) does not belong to Project Xaero's World Map (ID: 389665).
> Invalid file reference in manifest: File v22.13.2 for Forge 1.18.2 (ID: 3937634) does not belong to Project Xaero's Minimap (ID: 465575).
> Invalid file reference in manifest: File [1.18.2] YUNG's API v2.0.8 (Forge) (ID: 3779088) does not belong to Project YUNG's API (Forge) (ID: 631401).
> Invalid file reference in manifest: File [1.18.2] YUNG's Better Dungeons v2.1.0 (Forge) (ID: 3777934) does not belong to Project YUNG's Better Dungeons (Forge) (ID: 536660).
> Invalid file reference in manifest: File [1.18.2] YUNG's Better Mineshafts v2.2 (Forge) (ID: 3855186) does not belong to Project YUNG's Better Mineshafts (Forge) (ID: 480006).
> You can read more about this at https://support.curseforge.com/en/support/solutions/articles/9000197279-moderation-policies.
> 
> If you have any questions please contact our support team https://support.curseforge.com/.
</details>

With obviously mismatched `.pw.toml` files like every-compat.pw.toml

```toml
name = "Every Compat"
filename = "etched-forge-2.2.0+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "2907ebfd546e563be9cf489bcee5b56005695a2d"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3931285
project-id = 628539
```

**Comment by falxie** [comment]
I think the previous rejections were unrelated to that setting. It was probably just chance that when I changed it that the mods ended up being mismatched. See https://github.com/packwiz/packwiz/issues/150#issuecomment-1226761100
