### ISSUE TITLE
`packwiz curseforge detect` should work on resourcepacks folder

### ISSUE THREAD

**Issue by falxie** [packwiz/packwiz#153]
I noticed that only the mods folder's files are matched with their CurseForge counterparts. If possible it'd be ideal if resourcepacks could be detected as well.

**Comment by comp500** [comment]
I think this would be included as part of #66; that would let you specify any folder (or `.` for every folder) to match files from. (duplicate of #66)

**Comment by comp500** [comment]
Duplicate of #66 (why does Github not have a button to do this without making a commit)

**Comment by comp500** [comment]
Duplicate of #66
