### ISSUE TITLE
Add support for downloading resource packs from Modrinth

### ISSUE THREAD

**Issue by LithRakoon** [packwiz/packwiz#154]
Add support for installing resource packs now that they are available on modrinth.
this would make a great addition to Mr modpacks as they now would be able to pull resource packs straight from the site to have customizability in their modpacks

right now i get the error 
"failed installing mod: failed to get latest version: no valid versions found"
when using "packwiz mr install [resource pack ID]"

though ii suspect adding this might clog up the mod search result
possible fix to this is to use a flag:
packwiz mr install [resource pack ID] --resourcepack

**Comment by ryleu** [comment]
--rp would be a good shortening too

**Comment by LithRakoon** [comment]
Something like this could be nice too:
``packwiz mr install mod [slug]``
``packwiz mr install shader [slug]``
``packiwz mr install texture(?) [slug]``

**Comment by copygirl** [comment]
My intuition tells me since installing mods it what you'd most likely be doing, it perhaps should be the default, with `--shader` / `-s` and `--texture-pack` / `-t` or so as options to switch to different behavior - if the project type can't be automatically determined by the provided slug, URL or project ID.

**Comment by comp500** [comment]
Slugs are unique across all project types, there's no need to specify which you want to use (except for searching).

**Comment by comp500** [comment]
Fixed in https://github.com/packwiz/packwiz/commit/f3963ec1697e2cf13c41a4c3ad1c33fa141118ac - I've split the filtering options into a new issue https://github.com/packwiz/packwiz/issues/186.
