### ISSUE TITLE
Cannot accurately download the corresponding version of the mod

### ISSUE THREAD

**Issue by GodGun968** [packwiz/packwiz#158]
When I run `packwiz init` I select 1.19.2
but when I run `packwiz curseforge install memoryleakfix` it downloads [MemoryLeakFix - v0.7.0 for 1.19](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix/files/3912178) instead of [MemoryLeakFix - v0.7.0 for 1.19.x](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix/files/3908979)
However [MemoryLeakFix - v0.7.0 for 1.19](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix/files/3912178) not support 1.19.2 and running on 1.19.2 also gives an error
![image](https://user-images.githubusercontent.com/67826085/194301725-94aabdf7-f635-4565-878c-8faaedba8475.png)
![image](https://user-images.githubusercontent.com/67826085/194301260-87c5cda2-9787-455b-8068-84bc8e5601af.png)
![image](https://user-images.githubusercontent.com/67826085/194301593-e5f66e83-f1c5-4d37-ac30-0529cf6d8a34.png)
version:
https://github.com/packwiz/packwiz/actions/runs/2937095251 [Windows 64-bit](https://github.com/packwiz/packwiz/suites/8007249704/artifacts/343287555)

**Comment by comp500** [comment]
This is an issue with CurseForge's API - it thinks the 1.19 file is tagged for 1.19.2 and 1.19.1 as well (might have been originally uploaded as such then edited?)
![image](https://user-images.githubusercontent.com/1138417/194330519-176ed905-e810-4040-94a1-e5c2f48fbbd4.png)

The same occurs in the CurseForge Launcher: 
![image](https://user-images.githubusercontent.com/1138417/194331530-fc45fcdb-6104-4224-8a5c-cacbf1cfc79d.png)

**Comment by comp500** [comment]
The marked version in the game version column is *for 1.19*... this is an issue on CurseForge's end, raise it with them or the mod author (it might be fixable by editing the file again?)

**Comment by comp500** [comment]
Oh I thought you meant this by "game version column" 
![image](https://user-images.githubusercontent.com/1138417/194341257-4ea84f20-dbfb-40a6-8180-f1f3d369ef1a.png)

Anyway... no, packwiz does not scrape the CurseForge website, so it can't just see what is on the website. It uses [the CurseForge API](https://docs.curseforge.com/), which doesn't have the correct information! As I mentioned, report this problem to CurseForge or the mod author.

**Comment by comp500** [comment]
Yeah, that makes sense; as I said packwiz can't read this data, it must use the API.
