### ISSUE TITLE
Version pinning (skip updates in update --all)

### ISSUE THREAD

**Issue by lucasteo16** [packwiz/packwiz#164]
`packwiz update -all` simply updates all the mods it can, however, sometimes some of the mods are in alpha, beta or release stage that might be causing the game to crash. It would be nice to disable updates for specific mods (when doing update all) instead of doing the only alternative of typing every single other name of the mods that I want to update. Even more advance we can do something like `packwiz update -all -release` or adding an extra field within the mod toml file to disable update.

**Comment by copygirl** [comment]
Not a solution, but what I've done so far is to just run the `update --all` command, look at the list of changed files, and then revert the ones for mods that I did not want to update. Obviously this is only feasible when you've got version control set up with a GUI that easily allows you to revert changes.

**Comment by lucasteo16** [comment]
Alright then, so with your method, I'll just have to make sure I have a clean tree and run the following script to ignore changes for specific mods, nice. Okay now I just have to place these into a script file and job done.
```sh
packwiz update -all
git checkout HEAD -- ./mods/example-1.pw.toml
git checkout HEAD -- ./mods/example-2.pw.toml
packwiz refresh
```
Not a solution but a good workaround.

**Comment by comp500** [comment]
Of the possible solutions for this problem, a version pinning option (e.g. `packwiz pin <mod>` that sets a flag `pin = true`) seems like it would be the most elegant. It'd also be useful for the update confirmation dialog to allow interactively opting out of specific updates.

The pack format used to have a field for specifying the release channel so you could indicate that you only want to use release/beta versions; I never implemented it, so it was removed (but do I want to add it back, see https://github.com/packwiz/packwiz/issues/87)
