### ISSUE TITLE
`packwiz serve` should not require you to run `packwiz refresh --build` when `no-internal-hashes = true`

### ISSUE THREAD

**Issue by ChristopherHaws** [packwiz/packwiz#166]
I dont store hashes in my index files and instead run `packwiz refresh --build` in my automated build to make it simpler to manage with git. I would love it if I could run `packwiz serve` in this mode without having to add the hashes and then remove them before committing my changes.

Thanks!

**Comment by xieve** [comment]
This could be documented a bit better, it might not be the behavior one expects—the index is written to _when a download happens_, as far as I can tell. I would say ideally the hashes would be generated in memory and never written to disk?
