### ISSUE TITLE
Allow files and directories be ignored on export

### ISSUE THREAD

**Issue by KJP12** [packwiz/packwiz#170]
If files were manually edited via an IDE or anything else that tends to leave junk files behind, provide a way for `mr export` to exclude various files, likely either by `.gitignore` or specifying what to ignore by CLI.

*Yes, I manually edited the files to get around #169 as there was no better method available.*

**Comment by copygirl** [comment]
Like `.packwizignore`?

**Comment by KJP12** [comment]
Yes.

**Comment by copygirl** [comment]
Apologies. What I was trying to hint at is that this already exists, as can be seen in the [example pack](https://github.com/packwiz/packwiz-example-pack).

**Comment by comp500** [comment]
As copygirl mentioned, this already exists :)

**Comment by DadamaldaDad** [comment]
There is absolutely no mention of this in the docs.
