### ISSUE TITLE
Prefer MC versions in order of acceptable versions list (primary version first)

### ISSUE THREAD

**Issue by BelisariusMC** [packwiz/packwiz#181]
When using multiple acceptable game versions, some mods are installed using an older MC version even though a newer one is available. Example:

`minecraft = "1.19.3"`
`acceptable_versions = ["1.19.2", "1.19.1"]`

where the 1.19.2 version of the mods Debugify, Not Enough Crashes and Dash Loader are installed, when the 1.19.3 versions should be the most appropriate version.

My guess is that this occurs because some mods either:

1. have a version number higher for the older game version such as Debugify 1.1 (1.19.3) compared to 2.8.0 (1.19.2), and Not Enough Crashes 4.2.0+1.19.3 compared to 4.2.1+1.19.2; or 
2. the publish date for an older game version is more recent than for the current game version such as Dash Loader; or
3. the version formatting recently changed such as Iris Shaders 1.5.1+1.19.3 compared to 1.19.2-1.4.2.

List of known mods that I encountered where an older game version was unappropriated installed (for the above versions):

- Debugify (1)
- Not Enough Crashes (1)
- CraftPresence (2)
- Dash Loader (2)
- Essential Client (2)
- 3D Skin Layers (3)
- Iris Shaders (3)

***Tested only with Modrinth**

![image](https://user-images.githubusercontent.com/106339357/211444533-cef5b37b-0194-4065-9dce-a7eada4258b1.png)
![image](https://user-images.githubusercontent.com/106339357/211443727-705a2fa2-3ede-4370-8ac9-6a5e481664ef.png)
![image](https://user-images.githubusercontent.com/106339357/211444872-2ae8f114-175f-4e90-a229-89d79841ae1c.png)

**Comment by comp500** [comment]
Your guesses 1 and 3 are correct - packwiz doesn't use publish date, only the version number. A good improvement would be to prefer files using the primary Minecraft version, and treat the acceptable versions list as being in order of priority.

**Comment by IntoTheVoid-900** [comment]
Also happens with MoreCulling

**Comment by comp500** [comment]
I will note that I've implemented this in the reverse order (most preferred acceptable version is last) since I think most users have this set in ascending order - though of course the primary version is still used first
