### ISSUE TITLE
Unable to install shaders from modrinth

### ISSUE THREAD

**Issue by ryleu** [packwiz/packwiz#182]
Packwiz is unable to install shaders from modrinth, even when provided with a direct link. I'm not sure if this is within the scope of the project, but I have been using packwiz for managing shaders from CurseForge and Modrinth, I just have to do it manually.

**Comment by comp500** [comment]
See also https://github.com/packwiz/packwiz/issues/154

**Comment by comp500** [comment]
Fixed in https://github.com/packwiz/packwiz/commit/f3963ec1697e2cf13c41a4c3ad1c33fa141118ac
