### ISSUE TITLE
[STOP USING API v1] Modrinth API V1 Deprecated

### ISSUE THREAD

**Issue by OriginCode** [packwiz/packwiz#184]
When installing/updating a mod, there will be a prefix "[STOP USING API v1]".

It seems to be an issue with the Modrinth API version packwiz is using.

**Comment by OriginCode** [comment]
For reference: https://docs.modrinth.com/docs/migrations/v1-to-v2/

**Comment by comp500** [comment]
Update your version of packwiz, API v2 has been supported since August 2022.

**Comment by OriginCode** [comment]
> Update your version of packwiz, API v2 has been supported since August 2022.

Still exists after removing the whole go binary and installing by `go install github.com/packwiz/packwiz@latest`

**Comment by comp500** [comment]
Hmm, what does it print in the log when you run that command? What's the output of `go version`?

**Comment by OriginCode** [comment]
> Hmm, what does it print in the log when you run that command? What's the output of `go version`?

```
$ packwiz mr install iris
Found mod [STOP USING API v1] Iris Shaders: '[STOP USING API v1] A modern shaders mod for Minecraft intended to be compatible with existing OptiFine shader packs'.
Installing iris-mc1.19.2-1.4.3.jar from version 1.19.2-v1.4.3
```

`go version go1.19.4 linux/amd64`

**Comment by comp500** [comment]
I meant `go install github.com/packwiz/packwiz@latest` not the packwiz command :P

You could try removing packwiz from where the go command downloads it to, in `$GOPATH`.

**Comment by comp500** [comment]
I meant `go install github.com/packwiz/packwiz@latest` not the packwiz command :P

You could try removing packwiz from where the go command downloads it to, in `$GOPATH`.

**Comment by OriginCode** [comment]
> I meant `go install github.com/packwiz/packwiz@latest` not the packwiz command :P
> 
> You could try removing packwiz from where the go command downloads it to, in `$GOPATH`.

`go install github.com/packwiz/packwiz@latest` didn't produce any output.

I tried removing packwiz and reinstall it, no luck :(

**Comment by comp500** [comment]
Try removing the Go module cache in `$GOPATH/pkg/mod`? (`$HOME/go/pkg/mod` if GOPATH is not set)

**Comment by OriginCode** [comment]
> Try removing the Go module cache in `$GOPATH/pkg/mod`? (`$HOME/go/pkg/mod` if GOPATH is not set)

Yeah I removed the whole `$HOME/go` and reinstalling `packwiz` but the issue still exists

**Comment by comp500** [comment]
That's strange... Try disabling the go module mirror, by setting the `GOPROXY=direct` environment variable (see https://go.dev/ref/mod#private-module-privacy).

**Comment by OriginCode** [comment]
> That's strange... Try disabling the go module mirror, by setting the `GOPROXY=direct` environment variable (see https://go.dev/ref/mod#private-module-privacy). Also check where packwiz is installed from with `which packwiz`.

Oh I just found out I'm not using the one in `$HOME/go/bin` 😅

Sorry to bother you. It works now.
