### ISSUE TITLE
Recommended method for registering autocompletion for every session in macOS ZSH doesn't seem to work

### ISSUE THREAD

**Issue by gigawhip** [packwiz/packwiz#200]
`packwiz completion zsh -h` states:

```
To load completions for every new session, execute once:

#### macOS:

        packwiz completion zsh > $(brew --prefix)/share/zsh/site-functions/_packwiz
```

This successfully creates the file, but the file doesn't ever seem to get loaded. The per-session instructions do work - I can confirm that I've got completion functionality working in my shell and the completion script does work when its loaded. If it matters, this is on an M1 (ARM) MacBook.

There is a workaround: Adding the per-session recommendation (`source <(packwiz completion zsh); compdef _packwiz packwiz`) to `~/.zshrc` does provide completions for each session.

**Comment by comp500** [comment]
The completions and associated documentation are provided by [Cobra](https://github.com/spf13/cobra) - could you create an issue/PR or find a relevant one that already exists there? That should fix the issue for all users of Cobra too, not just packwiz :)

**Comment by gigawhip** [comment]
Thank you! Will do.

**Comment by gigawhip** [comment]
Aha. Seems to be a long-standing issue (https://github.com/spf13/cobra/issues/1529) and my workaround is suggested by some to actually be preferable. I don't think that issue is going to get closed anytime soon given the philosophical disagreement in that thread. If anyone else raises the issue for packwiz they should bump into my issue here which includes the workaround - I think that's sufficient. I recommend closing this ticket.
