### ISSUE TITLE
[Suggestion] Add an option so the user can specify the jar name

### ISSUE THREAD

**Issue by stantios** [packwiz/packwiz#210]
Description: I would like a feature added where the user can add an option in the mods .pw.toml (maybe the option can be called jar-name) to specify what jar name they would like the mod to have when running an export command or when downloading the mods of packwiz, this option would obviously be optional like all the other properties and I think this would help alot of modpack creators.

**Comment by comp500** [comment]
I'm not sure entirely what you mean by this... there is already a `filename` field that specifies the name the file should have when downloaded. Note that we have no control over the filename or folder a CurseForge file is downloaded to when exporting to the CurseForge modpack format.

**Comment by comp500** [comment]
> the destination of where the mod should be downloaded, not the name of jar file.

How are these different? Do you have an example?

**Comment by comp500** [comment]
I still don't see how these are different... taking for example my april fools mod in a test instance:
![image](https://user-images.githubusercontent.com/1138417/231604855-4e271049-6a42-4303-adce-8bcf60853c87.png)

This has a full path when installed of `...\PrismLauncher\instances\23w13a_or_b\.minecraft\mods\modvote-1.0.1+23w13a_or_b.jar`.  
The folder it's stored in is `mods`, and the jar file name is `modvote-1.0.1+23w13a_or_b.jar`, right?

For the `.pw.toml` metadata file in `mods` you'd therefore get something like:

```toml
name = "Mod Vote"
filename = "modvote-1.0.1+23w13a_or_b.jar"
side = "both"
# ...
```

The `filename` field is the same as the jar file name, as it specifies the name with which the file should be downloaded. It does also allow for relative paths (e.g. `../modvotemods/modvote-1.0.1+23w13a_or_b.jar`) but this isn't usually used.
