### ISSUE TITLE
Incorrect version resolution for Inventory Profiles Next and libIPN (on packwiz's end)

### ISSUE THREAD

**Issue by EthanZeigler** [packwiz/packwiz#215]
Currently, packwiz resolves modrinth's `inventory-profiles-next` with `fabric` and `1.19.4` to an incorrect dependency version. I've checked and that this isn't an issue on modrinth. It's packwiz.

**Steps to replicate**
- Create a new modpack with fabric (not quilt), mc 1.19.4 
- `packwiz modrinth install inventory-profiles-next`, include dependencies

**Expected**

- Inventory profiles next `fabric-1.19.4-1.9.7` installs
- libIPN `libIPN-fabric-1.19.4-2.0.4` installs

**Actual**

- Inventory profiles next `fabric-1.19.4-1.9.7` installs
- libIPN `libIPN-fabric-1.19.4-2.0.3` installs

**Additional details**
- Modrinth site and api resolves the libipn dependency to version id `lrTo7on9`, but packwiz installs `xctObNns`. It's not the first entry in the api response, so that's not it. The modrinth dependency api also explicitly states to install `lrTo7on9` so this has to be an implementation mistake on packwiz's side.

**Comment by comp500** [comment]
I can't replicate this issue, are you using the latest version of packwiz? Note that packwiz ignores the version ID in dependencies (as it might be older than the version you have installed, and usually you'll want to use the latest version anyway) but packwiz has had broken version ordering logic [until a recent fix](https://github.com/packwiz/packwiz/commit/42d8370d0cc749194922e461c145bc2cd1cc0de4).
