### ISSUE TITLE
application data is denied.

### ISSUE THREAD

**Issue by Interstellar73** [packwiz/packwiz#218]
Ive given full control for everyone to appdata, but when I run packwiz init, it gets to Refreshing index and then says: AppData\Local\Application Data: Access is denied.

how would I go about fixing this?

C:\Users\omitted>packwiz init
Modpack name [omitted]: test
Author: test
Version [1.0.0]: test
Minecraft version [1.19.4]: 1.19.4
Mod loader [quilt]: quilt
Quilt loader version [0.19.0-beta.13]: 0.19.0-beta.13
Refreshing index... 0 % [------------------------------------------------------------------------------] 4m56s
open AppData\Local\Application Data: Access is denied.

**Comment by comp500** [comment]
You need to make a folder specifically for your modpack, otherwise packwiz will try to include everything in your user directory in the modpack (including inaccessible or large files).

**Comment by Interstellar73** [comment]
how would I go about doing that? (selecting the folder for said modpack)

**Comment by comp500** [comment]
Change the folder you have your command prompt open in with the `cd` command - `C:\Users\omitted>` should update to show the directory you are in.

**Comment by Interstellar73** [comment]
thanks!
