### ISSUE TITLE
packwiz mr add --version-filename does nothing

### ISSUE THREAD

**Issue by MenacingPerson** [packwiz/packwiz#225]
Hey, so if I specify a version of a mod like so:
```
$ packwiz mr add qsl --version-filename 6.0.0-beta.7+0.81.1-1.19.4
Project "Quilted Fabric API (QFAPI) / Quilt Standard Libraries (QSL)" successfully added! (qfapi-6.0.0-beta.8_qsl-5.0.0-beta.9_fapi-0.82.0_mc-1.19.4.jar)
```

See how the wrong version has been added. The same happens if I use `qfapi-6.0.0-beta.7_qsl-5.0.0-beta.8_fapi-0.81.1_mc-1.19.4.jar` for the version filename. How do I fix this?

Thanks

**Comment by comp500** [comment]
As mentioned on Discord: `--version-filename` is intended for Modrinth versions that have multiple files (e.g. a sources jar, or an additional resource pack) to let you select which *file* to use, not for determining which *version* to use - you need to either:
- Use the URL for the version page: `packwiz mr add https://modrinth.com/mod/qsl/version/6.0.0-beta.7+0.81.1-1.19.4`
- Work out the version ID and use that with `--version-id`: `packwiz mr add --project-id qsl --version-id jCiJggRO`

**Comment by comp500** [comment]
Replied on Discord; created issues https://github.com/packwiz/packwiz/issues/226 https://github.com/packwiz/packwiz/issues/227
