### ISSUE TITLE
Add --side support for modrinth also

### ISSUE THREAD

**Issue by GameBurrow** [packwiz/packwiz#240]
Something I would like to see is a `--side`/`-s` option for `modrinth export` also, like `curseforge export` has.

**Comment by comp500** [comment]
Modrinth modpacks don't need this, they work for both sides by specifying which files are server-side/client-side, so you only need to distribute one `.mrpack`.

**Comment by GameBurrow** [comment]
> Modrinth modpacks don't need this, they work for both sides by specifying which files are server-side/client-side, so you only need to distribute one `.mrpack`.

The issue is that some serverside mods we have to keep using curseforge version (don't have alternatives for example). Using currently existing methods I can't upload the generated `.mrpack` file to modrinth because they check permissions and stuff for all mods, even server side (even if my project is configured as client only).

**Comment by comp500** [comment]
Hmm... I wonder if it'd be better to simply have a way of excluding mods from an export. Maybe a "tagging" system? I don't like having a `--side` flag in itself, it would likely mean that users just try to upload both packs to Modrinth unnecessarily and get their modpack rejected.

**Comment by GameBurrow** [comment]
Hmm, yes that could work. Could have option to both include only following tags or exclude following tags. Gives quite a lot of flexibility to everybody.

**Comment by comp500** [comment]
Closing in favour of https://github.com/packwiz/packwiz/issues/163
