### ISSUE TITLE
Add `resourcepack-folder` option

### ISSUE THREAD

**Issue by cschierig** [packwiz/packwiz#243]
I would like to autoload some resource packs by placing them in a directory similar to how adding data packs using packwiz works currently. Would it be possible to add a `resourpack-folder` option which does exactly that? If time's a problem I can implement it myself and open a pr.

**Comment by comp500** [comment]
You can just use the add command as usual then move the `.pw.toml` files to the right place (then using `packwiz refresh` to update the index).

`datapack-folder` only exists because there is no standard default location to place datapacks, so packwiz doesn't know where to put them.

**Comment by cschierig** [comment]
ok thanks for the quick response
