### ISSUE TITLE
Acceptable versions list says none.

### ISSUE THREAD

**Issue by Omay238** [packwiz/packwiz#255]
It should automatically have the version that the minecraft modpack is designed for, and maybe throw an error if you try to remove it. It looks weird when it says "Removed {VERSION} from acceptable versions list, now "

**Comment by comp500** [comment]
Hmm, this is a bit confusing UX wise as even in the TOML files it's not really clear that the acceptable versions list works in addition to the pack's own Minecraft version. I guess listing the main version in the list would make sense, just means it doesn't match up with what is in the TOML files.
