### ISSUE TITLE
slices.Compact

### ISSUE THREAD

**Issue by Deleplace** [packwiz/packwiz#257]
Hello, while researching for [this Go proposal](https://github.com/golang/go/issues/62729) I noticed [this code](https://github.com/packwiz/packwiz/blob/9889b48b0d475f3bc29b80e7c901f7b5c9336da0/modrinth/install.go#L291):

```
slices.Compact(depProjectIDPendingQueue)
```

which probably doesn't behave as intended and should look like this instead:

```
depProjectIDPendingQueue = slices.Compact(depProjectIDPendingQueue)
```

I have not tried to execute it.

**Comment by comp500** [comment]
Good catch, I think you are right from looking at how `slices.Compact` works - it would leave duplicate values at the end of the slice! This seems very counter-intuitive particularly as the documentation says `Compact modifies the contents of the slice s; it does not create a new slice.` and the similar `slices.Sort` function does not require this reassignment. I feel like it would be beneficial to also document this footgun in the `slices` documentation.
