### ISSUE TITLE
nix/vendorSha256 is empty

### ISSUE THREAD

**Issue by rwf93** [packwiz/packwiz#259]
As title is. Should be ``sha256-yL5pWbVqf6mEpgYsItLnv8nwSmoMP+SE0rX/s7u2vCg=`` as of 7e3ca8d9d54ec56d0ceaaca293e502c39d824422. I don't know if the system is automated. I assume vendor machine broke (:trollface:) and randomly removed it I guess.

**Comment by Whovian9369** [comment]
Bumping since it's still an issue that which makes the flake currently unusable.

**Comment by Whovian9369** [comment]
Just noticed [the failed GitHub Actions run](https://github.com/packwiz/packwiz/actions/runs/6603286849/job/17936225371#step:4:249) out of curiosity, and it looks like a Nix-related error broke it.

![image](https://github.com/packwiz/packwiz/assets/5240754/5ad3746d-c489-4cef-93a7-09a04abce66a)

**Comment by Whovian9369** [comment]
I got curious again, and decided to try fixing this. Seems like a quick one line fix should work fine to remedy this... I'll probably end up submitting a PR to fix it.

```diff
diff --git a/nix/prefetcher.nix b/nix/prefetcher.nix
index 3f8fb2d..a978e81 100644
--- a/nix/prefetcher.nix
+++ b/nix/prefetcher.nix
@@ -3,7 +3,7 @@
   pkgs ? import <nixpkgs> {},
 }:
 pkgs.callPackage (import ./.) {
-  buildGoModule = pkgs.buildGo118Module;
+  buildGoModule = pkgs.buildGo119Module;
   vendorSha256 = sha256;
 }
 // {
 ```
