### ISSUE TITLE
Git LFS file support when using GitHub Pages.

### ISSUE THREAD

**Issue by MaverickMartyn** [packwiz/packwiz#260]
When hosting through GitHub Pages, any files stored in Git LFS will fail to download.
If I recall correctly, Git LFS works by committing a small meta data file instead, and then storing the actual file elsewhere.
It looks like Packwiz just attempts to download the meta data file, since the resulting file has a different SHA256 hash, and is considerably smaller.
Here's an example where all the *.jar mod archives are stored in LFS: https://maverickmartyn.github.io/Gauntlet-of-Chaos/ 
Repo: https://github.com/MaverickMartyn/Gauntlet-of-Chaos 
It would be much preferable to use Github pages, since I could avoid hosting another website and keeping that up-to-date.

**Comment by copygirl** [comment]
When deploying your pack to Github Pages, it should ideally expand the .jar file but it looks like it [does not exist](https://maverickmartyn.github.io/Gauntlet-of-Chaos/mods/physics-mod-pro-v163a-forge-1.20.1.jar), as opposed to just a [mod that's just a metadata file](https://maverickmartyn.github.io/Gauntlet-of-Chaos/mods/oculus.pw.toml). I think this is a flaw in your deployment setup, rather than packwiz itself.

**Comment by MaverickMartyn** [comment]
That file doesn't exist, because the Pages are based on the _1.18.2-forge_ branch.
Here's a file with the problem: https://maverickmartyn.github.io/Gauntlet-of-Chaos/mods/lucky-block-forge-1.18.2-13.1.jar

**Comment by copygirl** [comment]
Well, both of those pages 404, for me.

**Comment by MaverickMartyn** [comment]
I actually just got it working!
I'm sorry, I should have let you know I was messing around with it.
The issue wasn't with Packwiz, but with the GitHub Pages build and deploy configuration.
In case anyone else runs into this, you have to create a GitHub Actions workflow, and set `lfs: true` in the correct step.
If you still want markdown to be transformed to a HTML site, you have to add a Jekyll step (at least if you base it on the "static" example.
I created a gist with my working workflow config, with relevant comments: https://gist.github.com/MaverickMartyn/826af9e77c8defc16c4955bc7904ce05
Thank you for your assistance regardless!
