### ISSUE TITLE
NeoForge Support

### ISSUE THREAD

**Issue by ChecksumDev** [packwiz/packwiz#268]
I'd like to know if there are any plans to support [NeoForged](https://neoforged.net/), as I have no plans with following Forge with many mods I use developing on the forked loader and the split in active development from the original Forge team.

It would be incredibly useful to have a packwiz integration like forge has right now, and its logic is likely similar to implement.

**Comment by Abalieno** [comment]
False.

![rtyukyil](https://github.com/packwiz/packwiz/assets/4656436/1b9de3ae-5e13-4515-a234-5b90bd3a29cd)

**Comment by ryleu** [comment]
looks to me like neoforge isn't available for that version yet.. which it wasn't when you wrote that. try it again

**Comment by comp500** [comment]
NeoForge is already supported, see https://github.com/packwiz/packwiz/commit/234f927be9ce70406731c1b1e3345324ae9862aa

**Comment by Abalieno** [comment]
Yet it doesn't work, see https://github.com/packwiz/packwiz/issues/268#issuecomment-1902660772

Are we playing some funny game?

**Comment by comp500** [comment]
No.. as @ryleu mentioned the error message was telling you that packwiz thinks there were no NeoForge versions available for Minecraft 1.20.4. It does seem that NeoForge has changed their versioning layout such that packwiz isn't currently able to see newer versions - that is a bug in packwiz - but that does not mean packwiz did not support NeoForge.

**Comment by Abalieno** [comment]
I don't know why you closed the issue since support for neoforge isn't functional. It was at least useful to indicate the problem was still open.
