### ISSUE TITLE
Error when adding Carpet-TCTC

### ISSUE THREAD

**Issue by Silverdev2482** [packwiz/packwiz#275]
I tried adding Carpet-TCTC but I got this error:
```
[silverdev2482@T480:~/Programming/Survival-mods]$ packwiz modrinth add Carpet TCTC
Searching Modrinth...
0) Cancel
1) *Carpet TCTC Addition
2) Carpet
3) Carpet-Fixes
4) Carpet TIS Addition
5) Carpet Extra
Choose a number:
1
Finding dependencies...
All dependencies are already added!
Failed to add project: version doesn't have a side that's supported. Server: unknown Client: unknown
```
I haven't had problems before adding mods, I also see a similar issue is opened here: https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/issues/24

**Comment by comp500** [comment]
This is an issue with the Modrinth website, I've reported it to Modrinth as requested in https://github.com/modrinth/labrinth/issues/644.
