### ISSUE TITLE
`winget` package

### ISSUE THREAD

**Issue by latipun7** [packwiz/packwiz#285]
Please consider releasing packwiz to Windows package manager, `winget`.
I don't know the detail of go project and how to release, but here is an example of release workflow: https://github.com/junegunn/fzf/blob/master/.github/workflows/winget.yml
Thank you.

**Comment by comp500** [comment]
Closing in favour of https://github.com/packwiz/packwiz/issues/219 - when I do versioned releases, they'll be published to a bunch of places.
