### ISSUE TITLE
NeoForge only recognizing 1.20.1 as valid version.

### ISSUE THREAD

**Issue by Omay238** [packwiz/packwiz#288]
I think it's an issue with the maven repo used, but I couldn't find a more accurate one.

**Comment by gjerm** [comment]
Looks like a more accurate one is here? https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml Not sure if it's a problem that it doesn't have MC versions listed

**Comment by urmet** [comment]
MC version is part of neogorge version number, not having it separately repeated isn't an issue.
examples:
MC 1.21.0 -> neoforge 21.0.x
MC 1.20.4 -> neoforge 20.4.x

**Comment by ToyVo** [comment]
on the neoforge version selector, it doesn't even have the 1.20.1 versions that page might be pulling from the newer metadata https://projects.neoforged.net/neoforged/neoforge
