### ISSUE TITLE
Latest version of packwiz expired

### ISSUE THREAD

**Issue by NightLighter423** [packwiz/packwiz#293]
On GitHub Actions it says that the latest version of the packwiz binaries have expired, please do something about this problem

**Comment by tboerger** [comment]
For those who can't or don't want to build the binaries on your own... I have published the binaries in the meantime to https://dl.webhippie.de/#minecraft/packwiz/20240325/.

I guess it's time to build a custom repository which just publishes releases somebody could rely on.

**Comment by NightLighter423** [comment]
> For those who can't or don't want to build the binaries on your own... I have published the binaries in the meantime to https://dl.webhippie.de/#minecraft/packwiz/20240325/.
> 
> I guess it's time to build a custom repository which just publishes releases somebody could rely on.

What if we have a repository which contains builds for other software as well

**Comment by Splarkszter** [comment]
in retrospective. it isn't hard to build this one. the instructions are on the readme of the main page.
It's literally two (or three) steps

0. Install golang-go in your machine
1. Download the repository
2. Run go install github.com/packwiz/packwiz@latest
wait for it to finish
done

**Comment by tboerger** [comment]
It's easy to build, right... But if you rely on it with some automation it sucks if the prebuilt binary URLs expire.

I'm automating the build of modpacks within github actions and I haven't been able build new pack versions. I have even created a github action to just download packwiz...

**Comment by bioastroiner** [comment]
> On GitHub Actions it says that the latest version of the packwiz binaries have expired, please do something about this problem

step 1: fork the project
step 2: enable workflows in Actions menu just hit that green button
step 3: commit something (just change a line in the readme.md) & push
step 4: enjoy and delete the fork

*ofc you shouldnt abuse this and make sure you remove the fork so it dosent clutter the repositories this is especialy useful for people who for some reason cannot build go projects localy on their machines (eg sanctions in my case)

**Comment by comp500** [comment]
I've merged some PRs, so there is now a new build. Sorry for the wait! (I will get to #219 hopefully soon!)

**Comment by NightLighter423** [comment]
Thx
