### ISSUE TITLE
Add a default .packwizignore ignoring git-related files

### ISSUE THREAD

**Issue by sdaugherty** [packwiz/packwiz#3]
The index.toml is updating hashes for git files, these should probably be ignored as it will result in repository and pack bloat when a pack is managed via a git repository.

**Comment by comp500** [comment]
I should probably document this somewhere - you can add a .packwizignore file in the same folder as pack.toml, with the lines `.git/` and `.gitignore` to ignore those files. It uses the same format as .gitignore.

I'll keep this issue open to remind me to make a default .packwizignore configuration for when there isn't one.
