### ISSUE TITLE
Why is this opening Discord?

### ISSUE THREAD

**Issue by CorneliusCornbread** [packwiz/packwiz#303]
Running `packwiz init` from the built binary and running through the options as follows I get the following CLI output?

```
Modpack name [USER]: Test
Author: CorneliusCorn
Version [1.0.0]: 2.3.0
Minecraft version [1.20.6]: 1.20.1
Mod loader [quilt]: forge
Forge version [47.2.32]: 
index.toml created!
open .config/discord/blob_storage/75046263-fd39-4ad5-a70e-a21020782a32: no such file or directory
```

Why is packwiz trying to open my discord's .config? I'd like to think this project isn't doing anything malicious but I'm not sure what else to think.

**Comment by CorneliusCornbread** [comment]
Doing some research, this application has apparently been known to access odd files? https://www.reddit.com/r/pcmasterrace/comments/12thn8n/i_may_have_installed_a_virus/

Discord I could see having value in reading files from it, Oculus too as you could in theory grab account data from both.

**Comment by TheEpicBlock** [comment]
Which exact binary did you download? I'm failing to reproduce this

**Comment by CorneliusCornbread** [comment]
> Which exact binary did you download? Or did you build yourself? I'm failing to reproduce this

I downloaded the binary from [this](https://github.com/packwiz/packwiz/actions/runs/8772389457) GH artifact for x86 Linux

**Comment by TheEpicBlock** [comment]
Hrmm, I can't reproduce. Nor can I find anything odd when running it through `strace`. Does packwiz always try to open discord files or is it only sometimes?

**Comment by CorneliusCornbread** [comment]
> Hrmm, I can't reproduce. Nor can I find anything odd when running it through `strace`. Does packwiz always try to open discord files or is it only sometimes?

It's every time I run it

**Comment by TheEpicBlock** [comment]
It seems that packwiz refreshes the index.toml right after the `index.toml created!` line. My suspicion would be that there's already something in the directory you're initializing which references the discord file.

**Comment by CorneliusCornbread** [comment]
> It seems that packwiz refreshes the index.toml right after the `index.toml created!` line. My suspicion would be that there's already something in the directory you're initializing which references the discord file.

I was running this in my home directory just for testing purposes. Though this wouldn't explain why it would be looking through Discord blobs.

**Comment by quat1024** [comment]
I'm not very familiar with Go, but here's where "index.toml created!" is printed

https://github.com/packwiz/packwiz/blob/9cca74476da41dafe85e04090d979921b55d6086/cmd/init.go#L136

and later it calls `index.Refresh()`, which calls [`filepath/WalkDir`](https://pkg.go.dev/path/filepath#WalkDir), which recursively scans all files in the directory to add them to the modpack

**Comment by CorneliusCornbread** [comment]
> Here's where "index.toml created!" is printed
> 
> https://github.com/packwiz/packwiz/blob/9cca74476da41dafe85e04090d979921b55d6086/cmd/init.go#L136
> 
> and later in this function it calls `index.Refresh()`
> 
> https://github.com/packwiz/packwiz/blob/9cca74476da41dafe85e04090d979921b55d6086/cmd/init.go#L171
> 
> which calls [`filepath/WalkDir`](https://pkg.go.dev/path/filepath#WalkDir)
> 
> https://github.com/packwiz/packwiz/blob/9cca74476da41dafe85e04090d979921b55d6086/core/index.go#L180
> 
> and WalkDir recursively searches inside subdirectories.
> 
> So this is kind of like running `git add .` from your home directory. It will try to add every file in your home directory into the modpack. If it doesn't have permission to open one of the files in your home directory (which I'm guessing is the case for this `.config/discord/blob_storage` file), it will error out on that file.
> 
> `packwiz init` should be ran from a directory containing only files intended for your modpack, as stated [in the documentation](https://packwiz.infra.link/tutorials/creating/getting-started/):
> 
> > To create the files for your new modpack, just run `packwiz init` in the folder you created!

Ahh, this makes sense, sorry, it's my first time trying out packwiz and I'm bouncing between a bunch of different problems with my server right now so I'm quite scatter brained. Thank you for the explanation
