### ISSUE TITLE
Packwiz init error

### ISSUE THREAD

**Issue by ilovethensa** [packwiz/packwiz#311]
When i run packwiz init i get
```
Failed to get latest minecraft versions: Get "https://launchermeta.mojang.com/mc/game/version_manifest.json": dial tcp 13.107.213.60:443: i/o timeout
```

**Comment by comp500** [comment]
Does https://launchermeta.mojang.com/mc/game/version_manifest.json work in your browser? It may have been an intermittent issue, try again if that link does work.

**Comment by ilovethensa** [comment]
Turns out there was a Microsoft azure outage that took down along with a lot of other stuff, the Minecraft servers so it wasn't an issue with packwiz
