### ISSUE TITLE
Packwiz curseforge export should not include the packwiz executable in overrides

### ISSUE THREAD

**Issue by GreatestFool** [packwiz/packwiz#37]
I think this should be rather obvious why it's a bad idea, considering the fact that curseforge are known to reject uploads that contain executables like this. I feel it is best to be on the safe side here.

**Comment by comp500** [comment]
It is intended that you copy the binary to your PATH (then you wouldn't have to have it in the same directory as your pack), but this sounds like a good check to have anyway - I'll add it at the same time as fixing #7.

**Comment by GreatestFool** [comment]
Sweet, thanks for the help! That also explains it. I'm using it through an alias and the variable is in the same folder while I'm testing to get used to stuff.
