### ISSUE TITLE
packwiz curseforge export to specified path

### ISSUE THREAD

**Issue by GreatestFool** [packwiz/packwiz#38]
This is probably related to #7 to some degree.

When using the `packwiz curseforge export` command, it'd be nice to be able to specify a path for it to export to after `export`. E.g. `packwiz curseforge export <path-to-export>`. Perhaps also have a default location, thus it could be added to the .packwizignore when using `packwiz init`.

This is probably relevant for the modrinth export command as well, now that I think about it, though I don't make use of this personally.

**Comment by comp500** [comment]
I have no idea why I didn't add a path argument in the first place, heh. You should be able to match wildcards in `.packwizignore` though, which should work with the current name + version filename, see https://git-scm.com/docs/gitignore#_pattern_format.

**Comment by GreatestFool** [comment]
Yup, that's what I'm currently doing. Though I made a small python script to both export it using packwiz and then move it into a specified folder to avoid having too much in the root directory :)
