### ISSUE TITLE
Dependency support for Modrinth

### ISSUE THREAD

**Issue by MrAn0nym** [packwiz/packwiz#56]
> Failed installing mod: json: cannot unmarshal object into Go struct field Version.dependencies of type string
- Trying to install modmanager (`packwiz modrinth install modmanager`)
- https://modrinth.com/mod/modmanager
- MR api for the specific version (`curl -i -s 'https://api.modrinth.com/api/v1/version/CdhVgHal'`):
`"dependencies":[{"version_id":"E4QBMVtO","dependency_type":"required"}]`

**Comment by comp500** [comment]
According to @wafflecoffee, dependencies aren't stable in the v1 Modrinth API, and not worth supporting yet (especially as they are not usable on the Modrinth website itself yet). For now, I'll stub out the dependency checking code, and add support once the v2 Modrinth API is ready.

**Comment by enderger** [comment]
@comp500 Now that the V2 API is in production, would reopening this issue be possible?
