### ISSUE TITLE
[Feature Request] packwiz edit

### ISSUE THREAD

**Issue by ExoPlant** [packwiz/packwiz#74]
Please add a `packwiz edit` command to edit metadata such as author, pack version, etc

**Comment by Den4enko** [comment]
> Please add a `packwiz edit` command to edit metadata such as author, pack version, etc

Try: packwiz init -r

**Comment by ExoPlant** [comment]
> > Please add a `packwiz edit` command to edit metadata such as author, pack version, etc
> 
> Try: packwiz init -r

Oh, does that work? Thanks!

**Comment by comp500** [comment]
Do note that `packwiz init -r` will overwrite the contents of `pack.toml`, so it might not be what you want for packwiz-gui. I suggest you use a [python TOML implementation](https://github.com/toml-lang/toml/wiki#implementations) to edit it for now.

**Comment by ExoPlant** [comment]
> Do note that `packwiz init -r` will overwrite the contents of `pack.toml`, so it might not be what you want for packwiz-gui. I suggest you use a [python TOML implementation](https://github.com/toml-lang/toml/wiki#implementations) to edit it for now.

I think we're doing that now
