### ISSUE TITLE
Don't filter by minecraft version & loader for non-mod projects

### ISSUE THREAD

**Issue by bravely-beep** [packwiz/packwiz#86]

**Comment by comp500** [comment]
This shouldn't be a problem, at least in terms of mod loader, for Modrinth or CurseForge now; CurseForge non-mod projects don't specify a loader (so packwiz allows any) and Modrinth non-mod projects are filtered appropriately (resource packs are always allowed).

I think filtering by game version is necessary; even non-mod projects will still break with new Minecraft versions.
