### ISSUE TITLE
"Set Fabric loader version" shows both values as new

### ISSUE THREAD

**Issue by Madis0** [packwiz/packwiz#90]
Reproduce:

1. Create a CF pack similar to Packwiz's that has the Fabric loader version updated
2. Import to Packwiz with `packwiz curseforge import filepath`
3. See the error

Expected:

> Set Fabric loader version to 0.13.2 (previously 0.13.1)

Actual:

> Set Fabric loader version to 0.13.2 (previously 0.13.2)

**Comment by comp500** [comment]
It's not really an error, just letting you know that the version was changed... but that message is wrong! I'll fix it now.
