### ISSUE TITLE
Package names aren't encoded

### ISSUE THREAD

**Issue by Madis0** [packwiz/packwiz#94]
Imported from CF to Packwiz

Got 

> filename = "entity-texture-features-[1.18.2]-2.4.5.jar"

but should be

> filename = "entity-texture-features-%5B1.18.2%5D-2.4.5.jar"

so when the wrong filename is used, packwiz bootstrapper fails to start:

![image](https://user-images.githubusercontent.com/8611110/157914049-9a33d36c-b7bb-4053-b673-6c78c242e0c2.png)

It is encoded correctly in the URL itself.

[Source file](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/Packwiz/1.18.2/mods/entity-texture-features-fabric.toml)

**Comment by comp500** [comment]
The filename shouldn't need to be encoded; this is something I want to fix in packwiz-installer, not packwiz (see https://github.com/packwiz/packwiz-installer/issues/5)
